import Link from "next/link";
import HeroScene from "@/components/portfolio/HeroScene";
import ProjectCard from "@/components/portfolio/ProjectCard";
import { getFeaturedProjects } from "@/lib/portfolioData";

export default async function PortfolioHome() {
  const projects = await getFeaturedProjects();

  return (
    <main className="relative overflow-hidden bg-surface-00">
      <div className="pointer-events-none absolute left-1/2 top-0 h-[680px] w-[680px] -translate-x-1/2 rounded-full bg-cyan-300/[0.055] blur-3xl" />
      <section className="portfolio-grid relative border-b border-white/10">
        <div className="mx-auto grid max-w-7xl items-center gap-10 px-6 pb-20 pt-16 sm:px-10 lg:min-h-[760px] lg:grid-cols-[1fr_.9fr] lg:gap-4 lg:px-12 lg:pb-24 lg:pt-20">
          <div className="relative z-10 max-w-3xl">
            <div className="mb-7 inline-flex items-center gap-3 rounded-full border border-cyan-200/20 bg-cyan-100/[0.06] px-4 py-2 font-mono text-[10px] uppercase tracking-[0.24em] text-cyan-100/80"><span className="h-2 w-2 animate-pulse rounded-full bg-cyan-200 shadow-[0_0_18px_#5ce1e6]" />Available for a few good problems</div>
            <h1 className="max-w-4xl text-[clamp(3.7rem,8vw,8.5rem)] font-semibold leading-[0.88] tracking-[-0.09em] text-white">Digital work<span className="block text-white/35">with a point</span><span className="block text-cyan-100">of view.</span></h1>
            <p className="mt-8 max-w-xl text-base leading-7 text-white/58 sm:text-lg">I design and build expressive products, brands, and interfaces where strategy, engineering, and atmosphere meet.</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/projects" className="rounded-full bg-cyan-100 px-6 py-3 text-sm font-bold text-surface-00 transition hover:bg-white">Explore selected work <span aria-hidden="true">↗</span></Link><Link href="/contact" className="rounded-full border border-white/15 px-6 py-3 text-sm font-semibold text-white/75 transition hover:border-white/40 hover:text-white">Start a conversation</Link></div>
            <div className="mt-14 grid max-w-xl grid-cols-3 gap-4 border-t border-white/10 pt-5"><Metric value="01" label="Clear strategy" /><Metric value="02" label="Crafted systems" /><Metric value="03" label="Brave details" /></div>
          </div>
          <div className="relative min-h-[440px] lg:min-h-[620px]"><div className="absolute inset-8 rounded-full bg-cyan-300/10 blur-3xl" /><HeroScene /><div className="absolute left-3 top-10 rounded-2xl border border-white/10 bg-black/20 px-4 py-3 backdrop-blur-xl sm:left-10"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-white/35">Current mode</div><div className="mt-1 text-sm font-semibold text-white/85">Build something memorable</div></div><div className="absolute bottom-14 right-2 max-w-[180px] rounded-2xl border border-white/10 bg-black/25 px-4 py-3 text-right backdrop-blur-xl sm:right-8"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-cyan-100/65">WebGL / Motion</div><div className="mt-1 text-xs leading-5 text-white/55">A small dose of depth makes a flat page feel alive.</div></div></div>
        </div>
      </section>
      <section className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-12"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Selected work / 001—003</p><h2 className="mt-4 max-w-xl text-4xl font-semibold tracking-[-0.06em] text-white sm:text-6xl">A few things I’m proud of.</h2></div><Link href="/projects" className="text-sm font-semibold text-cyan-100 transition hover:text-white">See the complete archive ↗</Link></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{projects.map((project, index) => <ProjectCard key={project.id} project={project} index={index} />)}</div></section>
      <section className="border-y border-white/10 bg-white/[0.025]"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-24 sm:px-10 lg:grid-cols-[.75fr_1.25fr] lg:px-12"><div><p className="eyebrow">How I work</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">Less noise.<br /><span className="text-white/35">More signal.</span></h2></div><div className="grid gap-4 sm:grid-cols-2"><Principle number="01" title="Make it make sense" text="A sharp point of view comes before a sharp interface. I make the story legible first." /><Principle number="02" title="Give it a pulse" text="Motion and 3D belong where they clarify, guide, or create a memorable moment." /><Principle number="03" title="Ship the details" text="The last 10%—states, edges, loading, type, and accessibility—is where trust lives." /><Principle number="04" title="Leave a system" text="You get a maintainable foundation, not just a pretty screenshot that cannot evolve." /></div></div></section>
      <section className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-12"><div className="relative overflow-hidden rounded-[2rem] border border-cyan-200/20 bg-[radial-gradient(circle_at_85%_20%,rgba(92,225,230,.2),transparent_32%),linear-gradient(120deg,rgba(255,77,157,.12),rgba(7,9,20,.9)_50%)] px-7 py-12 sm:px-12 sm:py-16"><div className="relative z-10 max-w-2xl"><p className="eyebrow text-cyan-100/70">Have a good brief?</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.06em] sm:text-6xl">Let’s make it impossible to ignore.</h2><p className="mt-5 max-w-lg text-sm leading-6 text-white/58">Tell me what you are building, where it is stuck, and what a great outcome looks like.</p><Link href="/contact" className="mt-8 inline-flex rounded-full bg-white px-6 py-3 text-sm font-bold text-surface-00 transition hover:bg-cyan-100">Open the conversation ↗</Link></div><div className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full border border-cyan-200/20 bg-cyan-200/[0.06] blur-[1px]" /><div className="pointer-events-none absolute -bottom-24 right-20 h-52 w-52 rounded-full border border-brand-pink/30 bg-brand-pink/10 blur-xl" /></div></section>
    </main>
  );
}

function Metric({ value, label }: { value: string; label: string }) { return <div><div className="font-mono text-xl text-cyan-100">{value}</div><div className="mt-1 text-[10px] uppercase tracking-[0.16em] text-white/35">{label}</div></div>; }
function Principle({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-2xl border border-white/10 bg-surface-00/50 p-5"><div className="font-mono text-xs text-brand-pink">{number}</div><h3 className="mt-8 text-lg font-semibold text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{text}</p></div>; }
